# Generated by Django 4.2.2 on 2024-07-22 16:53

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_username_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ethereum_wallet',
            field=models.CharField(blank=True, max_length=42, null=True, validators=[user.models.validate_ethereum_address]),
            preserve_default=False,
        ),
    ]
